# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-05 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_execution_time', models.DateField()),
                ('tradingsymbol', models.CharField(max_length=30)),
                ('trade_type', models.CharField(max_length=5)),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
