# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-05 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
